apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: intro
  # This is an extra long description with Markdown
  description: |
    [The Petstore](http://petstore.example.com) is an example API used to show features of the OpenAPI spec.
    - First item
    - Second item
    Key features and aspects of Java include:

Write Once, Run Anywhere (WORA): Java code is compiled into an intermediate form called bytecode, which can be executed on any device with a JVM. This makes Java highly portable and platform-independent.

Object-Oriented: Java is designed around the principles of object-oriented programming, which involves organizing code into reusable and modular components called objects.

Automatic Memory Management: Java uses a garbage collector to automatically manage memory, helping to prevent memory leaks and simplify memory management for developers.

Rich Standard Library: Java comes with a comprehensive standard library that provides a wide range of classes and methods for various tasks, such as networking, file I/O, database access, and more.

Multithreading: Java has built-in support for multithreading, allowing developers to create concurrent and parallel applications.

Security: Java has built-in security features, such as the ability to run applets in a secure sandbox environment. This makes it suitable for building secure applications, particularly in web development.

Community Support: Java has a large and active community of developers, which means there are numerous resources, libraries, and frameworks available for Java development.

Versatility: Java is used in a variety of applications, including web development (Java EE), mobile app development (Android), desktop applications, and enterprise systems.
  links:
    - url: https://github.com/swagger-api/swagger-petstore
      title: GitHub Repo
      icon: github
spec:
  type: service
  lifecycle: experimental
  owner: team-c
  providesApis:
    - petstore
    - streetlights
    - hello-world
