apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: intro
  # This is an extra long description with Markdown
  description: |
    
Java is a high-level, object-oriented programming language that was developed by Sun Microsystems (now owned by Oracle Corporation).
It was first released in 1995 and has since become one of the most widely used programming languages in the world. 
Java is known for its platform independence, which means that Java programs can run on any device or operating system that has a Java Virtual Machine (JVM) installed.
  links:
    - url: https://github.com/swagger-api/swagger-petstore
      title: GitHub Repo
      icon: github
spec:
  type: service
  lifecycle: experimental
  owner: team-c
  providesApis:
    - petstore
    - streetlights
    - hello-world